name: Semgrep - Team Vaccine

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep_check.yml
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: read

jobs:
  semgrep:
    if: github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
    name: semgrep/ci
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: semgrep/semgrep:1.136.0@sha256:cda1b566fafbf6010a02a3ea1d265b1c8eba4380e489a13891a102243d81ca6f
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN_VACCINE }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run Semgrep
        run: semgrep ci
